from fpdf import FPDF
from pathlib import Path

class PDFExporter:
    """
    Exports the final medical analysis to a professional PDF format.
    Requires the 'fpdf2' library.
    """
    def __init__(self):
        pass

    def export(self, report_text, image_path, output_path):
        """
        Creates a PDF report.
        
        Args:
            report_text (str): The text generated by MedicalReportGenerator.
            image_path (str/Path): Path to the Grad-CAM overlay image.
            output_path (str/Path): Where to save the PDF.
        """
        pdf = FPDF()
        pdf.add_page()
        
        # 1. Title
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(190, 10, "Brain MRI Analysis - Final Report", ln=True, align='C')
        pdf.ln(5)
        
        # 2. Add Image (Grad-CAM)
        if Path(image_path).exists():
            # Place image in the center
            pdf.image(str(image_path), x=50, y=None, w=110)
            pdf.ln(5)
        else:
            pdf.set_font("Arial", 'I', 10)
            pdf.cell(190, 10, "(Analysis visualization not available)", ln=True, align='C')
            pdf.ln(5)

        # 3. Add Report Text
        pdf.set_font("Arial", size=11)
        
        # Split text into lines to handle in fpdf
        for line in report_text.split('\n'):
            # Replace characters that might cause issues with latin-1
            # Replace em-dash with hyphen, etc.
            safe_line = line.replace('—', '-').replace('–', '-')
            
            # Encode/decode to strip anything else - aggressive ASCII fallback because FPDF is sensitive
            safe_line = safe_line.encode('ascii', 'replace').decode('ascii')
            
            # Use multi_cell with explicit width 190 (A4 is 210, default margins 10)
            if safe_line.strip():
                pdf.multi_cell(190, 6, safe_line)
            else:
                pdf.ln(6)
            
        # 4. Save
        try:
            pdf.output(str(output_path))
            print(f"PDF Report exported successfully to {output_path}")
        except Exception as e:
            print(f"Failed to save PDF: {e}")

if __name__ == "__main__":
    # Test with dummy data (expects fpdf installed)
    try:
        exporter = PDFExporter()
        # exporter.export("Sample Report Text", "dummy.jpg", "test.pdf")
    except Exception as e:
        print(f"PDF Export Test failed (likely missing fpdf): {e}")
