from datetime import datetime

class MedicalReportGenerator:
    """
    Generates human-readable medical reports from model predictions using
    template-based Natural Language Generation (NLG).
    """
    def __init__(self):
        # Professional medical-style descriptions for each class
        self.clinical_descriptions = {
            'glioma': (
                "The image features are suggestive of a glioma, a type of tumor that occurs in the brain and spinal cord. "
                "Gliomas begin in the glial cells that surround nerve cells and help them function. "
                "Findings often include varying degrees of mass effect and peritumoral edema."
            ),
            'meningioma': (
                "The analysis indicates characteristics consistent with a meningioma. "
                "These are typically slow-growing tumors that arise from the meninges - the membranous layers surrounding the brain. "
                "Common radiographic features include well-circumscribed borders and potential dural tail sign."
            ),
            'pituitary': (
                "The imaging highlights abnormalities in the sellar region, consistent with a pituitary tumor. "
                "These tumors develop in the pituitary gland and can affect hormone levels or visual fields due to proximity to the optic chiasm. "
                "Regular clinical correlation with endocrine function is typically recommended."
            ),
            'notumor': (
                "The automated analysis did not identify any significant masses or lesions consistent with the target tumor types. "
                "Anatomical structures within the provided field of view appear within normal limits for this screening protocol."
            )
        }
        
        # Short clinical summaries for NER and Chatbot processing
        self.findings_snippets = {
            'glioma': "Suggestive of an intra-axial mass in the glial tissues, consistent with glioma features.",
            'meningioma': "Findings indicate a well-circumscribed extra-axial lesion near the meninges, suggestive of meningioma.",
            'pituitary': "Identification of a mass in the sellar region, consistent with pituitary adenoma characteristics.",
            'notumor': "No significant intracranial masses or abnormal enhancement patterns were detected."
        }

    def get_clinical_findings(self, predicted_class):
        """Returns a short 1-2 sentence findings text for NLP processing."""
        return self.findings_snippets.get(predicted_class.lower(), "Observations inconclusive.")

    def generate_report(self, predicted_class, confidence, gradcam_observation=None):
        """
        Generates a structured medical report.
        
        Args:
            predicted_class (str): The class identified by the model.
            confidence (float): The probability score (0-1).
            gradcam_observation (str, optional): Qualitative remark from the explainability module.
            
        Returns:
            str: The formatted report.
        """
        date_str = datetime.now().strftime("%Y-%m-%d %H:%M")
        
        # Determine status string based on confidence
        if confidence > 0.85:
            status = f"High-confidence identification"
        elif confidence > 0.60:
            status = f"Moderate-confidence identification"
        else:
            status = f"Preliminary identification (low-confidence)"

        report = [
            f"DATE: {date_str}",
            "",
            f"PRIMARY FINDING: {predicted_class.upper()}",
            f"STATUS: {status}",
            f"CONFIDENCE SCORE: {confidence:.2%}",
            "",
            "CLINICAL OVERVIEW:",
            self.clinical_descriptions.get(predicted_class.lower(), "Description not available."),
            ""
        ]

        if gradcam_observation:
            report.append("EXPLAINABILITY OBSERVATION (Grad-CAM):")
            report.append(gradcam_observation)
            report.append("")

        report.append("------------------------------------------------------------")
        report.append("DISCLAIMER:")
        report.append(
            "This report is generated by an Artificial Intelligence system for research and "
            "educational purposes only. It DOES NOT constitute a medical diagnosis. "
            "All findings must be reviewed and validated by a board-certified radiologist "
            "and correlated with clinical symptoms and laboratory data."
        )
        report.append("------------------------------------------------------------")
        
        return "\n".join(report)

if __name__ == "__main__":
    # Quick self-test
    gen = MedicalReportGenerator()
    print(gen.generate_report("glioma", 0.942))
